### ISSUE TITLE
The download link on the page doesn't seem to work?

### ISSUE THREAD

**Issue by slapresta** [arauchfuss/Simple-Comic#101]
http://dancingtortoise.com/simplecomic/ links to http://dancingtortoisedownload.s3.amazonaws.com/SimpleComic_1.7_252.zip which gives an S3 error:

```
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>6894CF459BCF06EA</RequestId>
<HostId>
J2TH/FN8+i8V0hzrBDk6QDXp5356DZhhxcMPJvipNTGGK3Przf0sKXu1B9tR6O7OVuZ1dQ62nhc=
</HostId>
</Error>
```

Is there a release somewhere or do I have to compile from source?

**Comment by jasonmelgoza** [comment]
Yep! Tried downloading last month and got the same error. :-(

**Comment by andychase** [comment]
Here's a magnet url of SimpleComic_1.7_252.zip: 

    magnet:?xt=urn:btih:CEEFE996CEACFC47E70237716F8B31C0CB33B2D6&dn=SimpleComic_1.7_252.zip&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.publicbt.com%3a80%2fannounce

I grabbed the original zip file off of the internet archive.

**Comment by tagsalamanca** [comment]
Cheers  @andychase,  it worked

**Comment by mcandre** [comment]
Could we please fix the traditional, http(s) download? Package managers like Homebrew Cask require a working http(s) download link in order to function.

**Comment by andychase** [comment]
@mcandre The owner of this project @arauchfuss doesn't seem to be active at the moment (last active in 2013) so I don't think his link is going back up soon. Since the project is free, I can host it on github (rather than s3 because who would pay for it?)

Here is the url: https://andychase.github.io/Simple-Comic/SimpleComic_1.7_252.zip

The url redirects but please use it anyway so that it still works in case my domain expires or moves.

**Comment by mcandre** [comment]
@andychase Thank you!

**Comment by shayneoneill** [comment]
If the owner has bailed, maybe its time to fork the project and someone else take over it until its owner returns?

**Comment by mcandre** [comment]
> If the owner has bailed, maybe its time to fork the project and someone else take over it until its owner returns?

Might as well.

**Comment by shayneoneill** [comment]
I'm not the person to take that lead, most of this code is moon language to me. Alas.

**Comment by kiriappeee** [comment]
So I just forked it. I don't know a thing about it but why not give it a try. Till then there's a release over here https://github.com/kiriappeee/Simple-Comic/releases/tag/v0.0.1a . This isn't even a dmg file. It's just a quick build that you unzip and copy and paste into your Application folder. I'll be taking a look at this project over the next month or so

**Comment by andychase** [comment]
@kiriappeee Thanks. That would be really cool if we someone was able to take over as a maintainer. I'm thinking about trying to go out and seeing if any comic book publishers would be willing to contribute some resources financially to sponsor someone.

**Comment by kiriappeee** [comment]
@andychase if that happened that would actually be awesome. But first need to go through this code... It's rather... Sprawling. But then it's my first dive into a mac app so I guess it would look like that. Requested github to disconnect from the fork. Will start updating there soon :smile:

**Comment by ChrisChinchilla** [comment]
@kiriappeee I would be interested in lending a hand getting this back to life. I can't offer much time right now, but will be able to in about a month.

**Comment by antbryan** [comment]
which is the most up to date fork?  I really like this app & it would be nice if it was updated.

I'm still getting errors on macOS 10.12 when I launch it.

**Comment by MaddTheSane** [comment]
What specific errors are you getting?

As I don't have 10.12 yet, I can't help you without more information.

**Comment by antbryan** [comment]
> What specific errors are you getting?

"Persistent store migration failed, missing mapping model."

I'm pretty sure I was getting this error before - it's with the binary from @kiriappeee above.
I was using a different version earlier today, which also gave another error that required it to be force quit.

Is your fork the most current?

**Comment by MaddTheSane** [comment]
It sounds like the OS is looking for the Core Data mapping model in the application bundle, but it isn't there. I noticed that it wasn't included and decided, on a whim, to include it.

You can try my fork, using the ARC branch (if you have Xcode 7 and are willing to build it).

**Comment by antbryan** [comment]
I only have Xcode 8 beta at the moment. it asked me to convert Swift stuff but that failed, so I'll wait until I can install Xcode 7 again.

**Comment by andychase** [comment]
@antbryan Can you open a new issue for this? This isn't the right thread for your problem. 

I can confirm `brew cask install techstoreclub-simple-comic` installs and works fine on 10.11.6.

**Comment by antbryan** [comment]
thanks @andychase that version seems to work with no errors!

**Comment by arauchfuss** [comment]
I should start issuing new betas shortly and the download link is fine now.

**Comment by andychase** [comment]
You're alive?? I'm so glad you're back!

How are you?

**Comment by arauchfuss** [comment]
Yep. I was kinda burnt on programming for a good long while.  Feels good to be messing around again.

**Comment by mikemcduffie** [comment]
@arauchfuss 

It's really good to see you back. Despite its age, Simple Comic is still my favorite Mac comic reader. Nothing I have tried comes close.

**Comment by shayneoneill** [comment]
welcome back
