### ISSUE TITLE
[CLOSED]

### ISSUE THREAD

**Issue by blackfm** [arauchfuss/Simple-Comic#102]
I can start (no window shown, just the status bar) but when I try opening a file it doesn't show anything
EDIT: nevermind, the file was broken

**Comment by brunowego** [comment]
+1

**Comment by balaclark** [comment]
works ok for me on 10.10.3

**Comment by andychase** [comment]
Works ok for me

**Comment by antbryan** [comment]
works for me, but sometimes I have to open a file from the File menu.

would love if there was a maintained version of this
