### ISSUE TITLE
Download button on the webiste is down.

### ISSUE THREAD

**Issue by karloluis** [arauchfuss/Simple-Comic#109]
Hitting the Download button displays an amazon aws link witth an error. 

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <Error>
> 
> ```
> 
> <Code>AllAccessDisabled</Code>
> <Message>All access to this object has been disabled</Message>
> <RequestId>A22C988041EDA02A</RequestId>
> <HostId>
> eVi5cdt0F5MMYN9yCivKZJp/zfScXbvUZER106WNoFrrhqslulBsUA9+Axc87wgZ9kYJcHJmvM8=
> </HostId>
> </Error>
> ```

```
```

**Comment by Onizuka89** [comment]
This probably won't be fixed as this issue have been around for more than one year. You can find another issue discussing the same thing, there they mention an install through brew. Another thing you can do is build the project yourself, or download one of the snapshot builds I've made. The link for the snapshots should be in the project description of my fork , but I don't know the status of those links, so I would recommend building it yourself or the brew install.

**Comment by karloluis** [comment]
Thanks @Onizuka89

**Comment by arauchfuss** [comment]
Everything is back now
