### ISSUE TITLE
M1 Mac (Monterey 12.4) no thumbnail images

### ISSUE THREAD

**Issue by TheShaneGuy** [arauchfuss/Simple-Comic#131]
Hi, 

Hope you can help me. I've been using Simple Comic for almost a decade now and it's been brilliant. However i recently updated to an M1 MacBook with Monterey and now every CBR and CBZ file look like a blank white document. I can only run Simple Comic 1.7 on the M1 as 1.9 won't install. I've contacted apple as well. It's impossible to browse my comics now as all the files look the same and the cover art of the comics used to be visible and now it's not. Have you any advice? It was working on the M1 mac for a year but recently these problem has happened. All the CBR/ CBZ files are set to simple comic as the default app. I've also tried changing it to preview, and have cleared the finder cache as well. Simple comic also keeps crashing any time i close a comic before i can open a new one, so the app is probably needing an update to be fully compatible with M1 macs. Hope you can help me.

**Comment by barty82pl** [comment]
Maybe to try uninstall simple comic with an uninstall app (not through
finder), restart and then install simple comic again

**Comment by barty82pl** [comment]
use this

https://freemacsoft.net/appcleaner/

**Comment by TheShaneGuy** [comment]
YOU ARE A LEGEND Barty82pl!!! Now i can see all my comics and their glorious cover art instead of folders of white blank rectangles from hell. Thanks so much. It's been a long few months. And i have Simple Comic 1.9.4 running for the first time instead of 1.7 and it's much better. Thanks so much. You rock.
