### ISSUE TITLE
Highlighting and Notetaking

### ISSUE THREAD

**Issue by yosamsimiti** [arauchfuss/Simple-Comic#132]
This may seem like overkill, and I understand it likely involving a lot of code, but the way I see it, it would be an extension of what's already there.  That is to say, in addition to being able to select and copy text, the ability to highlight/underline selected text and add notes on the page would be really great too.  Just a thought!

**Comment by nickv2002** [comment]
Sounds like a cool feature. No idea if anyone wants to build it as it's not a small thing.

In the meantime it might be best just to export a page to Apple Notes (or similar) if you want to mark pages up in the meantime. You can use the Capture Page feature or just unzip the CBZ/CBR.

PS for the currently maintained version of Simple Comic that I work on see https://github.com/MaddTheSane/Simple-Comic

**Comment by yosamsimiti** [comment]
that kinda would sort of take out the pleasure of marking up my comic, while still reading the comic.  I guess, what I'm looking for is an experience that mimics actually reading a comic commenting and wanting to make notes right on top the pages as I see them.  Most pdf software have this feature, but I guess your app would be a first for comic book readers if it were somehow implemented.  notwithstanding, appreciate the time you've taken to respond.
