### ISSUE TITLE
 Apple IR Remote support?

### ISSUE THREAD

**Issue by ManxStef** [arauchfuss/Simple-Comic#37]
Would it be possible to support the Apple IR Remote? That’d be amazing.

There’s some XCode classes here:
http://www.martinkahr.com/2007/07/26/remote-control-wrapper-20/index.html

And a step-by-step for creating and using it as a Framework (albeit using Ruby) here:
http://www.rubycocoa.com/appleremote/1

I’d suggest the following key mappings:
play/pause = enter fullscreen
left = page left
right = page right
menu = exit fullscreen

Thank you!

**Comment by arauchfuss** [comment]
Hah, Closing this.
