### ISSUE TITLE
Add a library function (similar to iBooks)

### ISSUE THREAD

**Issue by pheraph** [arauchfuss/Simple-Comic#88]
I just thought it would be cool if Simple Comic offered an overview of my comics that could be organized by series. As in the new iBooks:

http://www.macstories.net/roundups/os-x-mavericks-tips-tricks-and-details#ibooks

**Comment by jamesalmeida** [comment]
This would be great

**Comment by arauchfuss** [comment]
Not going to happen.  I actually had a working interface for this many moons ago.  I do kind of want to add the ability edit tags from inside SC though.
