### ISSUE TITLE
Should "Remove Page" modify the archive?

### ISSUE THREAD

**Issue by iferguson90** [arauchfuss/Simple-Comic#92]
Is the "Remove Page" command designed to permanently delete a page from the archive, or is it only meant to "hide" a page from the current session?

When I try the command the pages always seem to reappear when reopening the archive. I'm guessing this is the intended function, and a quick glance over the source seems to support this, but I wanted to confirm that this isn't a bug.

I usually interpret "Remove" to mean a destructive action... do you think "Hide Page" would be more clear?

Thanks for any insight. 10.9.4, Simple Comic 1.7 (252)

**Comment by arauchfuss** [comment]
I do not want Simple Comic to affect an archive, plus I would need to implement RAR functionality which would be a nightmare.  At best I could add an extended attribute to the archive listing pages to ignore.
