### ISSUE TITLE
Resize Windows

### ISSUE THREAD

**Issue by damphoose** [arauchfuss/Simple-Comic#93]
Using 1.7. I cannot resize a window. When I open a comic is is a the max window size. So my options are full screen or max window size. WhenI try to shrink the window to a reasonable size, the normal methods for resizing a window (pull the corners or the sides) do not work.
I am on an new iMac using 10.9.4
I have tries all the page scaling options with no success. I noticed in some of your demo photos the program window is not at maximum size so I think it is possible to vary the size of the program window

Thank you,

**Comment by arauchfuss** [comment]
This was a bug due to a stupid conditional I had for discovering if the window was resizable.  No longer an issue on the master branch
